alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias cls='clear'

##
#alias "kdev1"='kubectl config use-context kube-dev-au-01'
alias "kdev2"='kubectl config use-context kube-dev-au-02'
alias "kjenk"='kubectl config use-context kube-jenkins'
alias "ktrain"='kubectl config use-context kube-training'
alias "kprod1"='kubectl config use-context kube-prod-au-01'
alias "kprod2"='kubectl config use-context kube-prod-au-02'
alias "aksdev1"='kubectl config use-context aks-aus-dev-01-admin'
alias "aksdev2"='kubectl config use-context aks-aus-dev-02-admin'
alias "aksjenk"='kubectl config use-context kube-jenkins-admin'

alias "kcfg"='kubectl config'
alias "kproxy"='kubectl proxy &'
alias "kgt"='kubectl get'
alias "kget"='kubectl get'
alias "kg"='kubectl get'
alias "kdel"='kubectl delete'
alias "kdl"='kubectl delete'
alias "kdes"='kubectl describe'
alias "kds"='kubectl describe'
alias "kpf"='kubectl port-forward'
alias "kapply"='kubectl apply'
alias "ka"='kubectl apply'
alias "kscale"='kubectl scale'
alias "ks"='kubectl scale'
alias "krun"='kubectl run'
alias "kr"='kubectl run'
alias "kedit"='kubectl edit'
alias "ke"='kubectl edit'
alias "ktop"='kubectl top'
alias "kt"='kubectl top'
alias "kshell"='kubectl run my-shell --rm -i --tty --image docker.io/voltaireilustrisimo/my-shell:ubuntu1804 -- bash'

#
alias "dps"='docker ps -a'
alias "drm"='docker rm -f'
alias "drmall"='docker rm -f $(docker ps -aq)'
alias "di"='docker images'
alias "drmi"='docker rmi -f'
alias "drmiall"='docker rmi f $(docker rmi -f $(docker images -aq)'
alias "dbuild"='docker build'
alias "drun"='docker run'
alias "pshell"='pwsh'

alias "kcreate"='kubectl create'
alias "kc"='kubectl create'
alias "kexec"='kubectl exec'
alias "kx"='kubectl exec'
alias "kxi"='kubectl exec -it'
alias "klogs"='kubectl logs'
alias "kl"='kubectl logs'
alias "k"='kubectl'
alias "flushdns"='sudo /etc/init.d/dns-clean'

alias "viber"='cd /home/voltaire/.local/share/applications/ && sudo ./viber.desktop'
